### ISSUE TITLE
Can not control Denon X4400H since last update

### ISSUE THREAD

**Issue by garfieldhy** [grzegorz914/homebridge-denon-tv#101]
[5/1/2021, 9:51:56 PM] [DenonTv] Device: 192.168.1.160 Denon Z2 Zone 2, can not set new Power state. Might be due to a wrong settings in config, error: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read',
  config: [Object],
  request: [Writable],
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
[5/1/2021, 9:51:58 PM] [DenonTv] Device: 192.168.1.160 Denon X4400H Main Zone, can not set new Power state. Might be due to a wrong settings in config, error: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read',
  config: [Object],
  request: [Writable],
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}

**Comment by grzegorz914** [comment]
Please check Your config

**Comment by garfieldhy** [comment]
Thanks for the reply. I dont know what's wrong with my settings but everything used to be fine before updating.

**Comment by grzegorz914** [comment]
Please enable Debug mode and get the log.

**Comment by garfieldhy** [comment]
[5/2/2021, 8:47:35 AM] [DenonTv] Device: 192.168.1.160 Denon X4400H, requesting Device Info.
[5/2/2021, 8:47:35 AM] [DenonTv] Device: 192.168.1.160 Denon Z2, requesting Device Info.
[5/2/2021, 8:47:37 AM] [DenonTv] Device: 192.168.1.160 Denon Z2, get device info error: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read',
  config: [Object],
  request: [Writable],
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}, device offline, trying to reconnect
[5/2/2021, 8:47:37 AM] [DenonTv] Device: 192.168.1.160 Denon X4400H, get device info error: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read',
  config: [Object],
  request: [Writable],
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}, device offline, trying to reconnect

**Comment by garfieldhy** [comment]
[5/2/2021, 8:51:21 AM] [homebridge-denon-tv] Error: 
    at Accessory.sendCharacteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1874:14)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1596:16)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)

**Comment by grzegorz914** [comment]
Check Your network settings, IP, Port, power OFF and ON Receiver, make sure Your AVR is available on the network.

**Comment by garfieldhy** [comment]
I checked the internet connection on my receiver, it passed all test. Then I unplugged the receiver and replugged it, the home app works now! Thanks!
