### ISSUE TITLE
Device not detected in Home, and not initialized in logs.

### ISSUE THREAD

**Issue by Seexelas** [grzegorz914/homebridge-denon-tv#122]
Hi Grzegorz914,

I had to reinstall my Raspberry with my Homebridge since it crashed. I fresh installed everything.

HB Version 1.3.8
Node.js Version v16.13.0
Npm Version v8.1.4

I can reach my Denon by HTTP/HTTPS, so it's responding on my network. 

The plugin configuration : 
[
                {
                    "name": "Denon X-4500H",
                    "host": "192.168.1.11",
                    "refreshInterval": 5,
                    "zoneControl": 0,
                    "volumeControl": 0,
                    "masterPower": false,
                    "masterVolume": false,
                    "masterMute": false,
                    "switchInfoMenu": false,
                    "disableLogInfo": false,
                    "inputs": [
                        {
                            "name": "Apple TV",
                            "reference": "MPLAY"
                        }
                    ]

I have no error message in the logs : 

Only ma Harmony plugin is initializred : 
[27/11/2021, 21:18:09] [HB Supervisor] Restarting Homebridge...
[27/11/2021, 21:18:09] [HB Supervisor] Starting Homebridge with extra flags: -I
[27/11/2021, 21:18:09] [HB Supervisor] Started Homebridge v1.3.8 with PID: 1006
[27/11/2021, 21:18:10] Loaded config.json with 0 accessories and 3 platforms.
[27/11/2021, 21:18:11] Loaded 0 cached accessories from cachedAccessories.
[27/11/2021, 21:18:11] ---
[27/11/2021, 21:18:13] Loaded plugin: homebridge-config-ui-x@4.41.3
[27/11/2021, 21:18:13] Registering platform 'homebridge-config-ui-x.config'
[27/11/2021, 21:18:13] ---
[27/11/2021, 21:18:13] Loaded plugin: homebridge-denon-tv@3.12.16
[27/11/2021, 21:18:13] Registering platform 'homebridge-denon-tv.DenonTv'
[27/11/2021, 21:18:13] ---
[27/11/2021, 21:18:13] Loaded plugin: homebridge-harmony@1.5.3
[27/11/2021, 21:18:13] Registering platform 'homebridge-harmony.HarmonyHubWebSocket'
[27/11/2021, 21:18:13] ---
[27/11/2021, 21:18:14] Loaded plugin: homebridge-vieramatic@3.2.4
[27/11/2021, 21:18:14] Registering platform 'homebridge-vieramatic.PanasonicVieraTV'
[27/11/2021, 21:18:14] ---
[27/11/2021, 21:18:14] Loading 3 platforms...
[27/11/2021, 21:18:14] [Config] Initializing config platform...
[27/11/2021, 21:18:14] [Config] Running in Service Mode
[27/11/2021, 21:18:14] [Harmony] Initializing HarmonyHubWebSocket platform...
[27/11/2021, 21:18:14] [Harmony] HarmonyPlatform Init
[27/11/2021, 21:18:14] [DenonTv] Initializing DenonTv platform...
[27/11/2021, 21:18:14] [Harmony] DidFinishLaunching
[27/11/2021, 21:18:14] [Harmony] (Harmony)INFO - Loading activities...
Setup Payload:
X-HM://0024YWK60NZWF
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 906-52-696 │     
    └────────────┘     
                       
[27/11/2021, 21:18:14] Homebridge v1.3.8 (HAP v0.9.7) (Homebridge) is running on port 51790.
[27/11/2021, 21:18:15] [Harmony] (Harmony)INFO - Adding Accessory : Harmony-TV
[27/11/2021, 21:18:15] [Harmony] (Harmony)INFO - configuring Main TV Service
[27/11/2021, 21:18:15] [Harmony] (Harmony)INFO - Creating TV Service
[27/11/2021, 21:18:15] [Harmony] (Harmony)INFO - Creating Input Service - Gaming PC
[27/11/2021, 21:18:15] [Harmony] (Harmony)INFO - Creating Input Service - Amazon Prime
[27/11/2021, 21:18:15] [Harmony] (Harmony)INFO - Configuring Main Activity Apple Tv
[27/11/2021, 21:18:15] [Harmony] (Harmony)INFO - Creating TV Speaker Service
[27/11/2021, 21:18:15] [Harmony] (Harmony)INFO - Creating Input Service - Apple Tv
[27/11/2021, 21:18:15] [Harmony] (Harmony)INFO - Creating Input Service - Xbox S. X
[27/11/2021, 21:18:15] [Harmony] (Harmony)INFO - Creating Input Service - PS 5
[27/11/2021, 21:18:15] [Harmony] (Harmony)INFO - Creating Input Service - Retro Gaming
[27/11/2021, 21:18:15] [Harmony] (Harmony)INFO - Creating Input Service - Netflix
[27/11/2021, 21:18:15] [Harmony] (Harmony)INFO - Creating Input Service - Switch
[27/11/2021, 21:18:15] [Harmony] (Harmony)INFO - Creating Input Service - Mister FPGA
[27/11/2021, 21:18:15] [Harmony] (Harmony)INFO - Creating Input Service - 4K Bluray
[27/11/2021, 21:18:15] [Harmony] (Harmony)INFO - setupFoundAccessories - TV accessory added as external accessory
[27/11/2021, 21:18:16] Harmony-TV A2D1 is running on port 38343.
[27/11/2021, 21:18:16] Please add [Harmony-TV A2D1] manually in Home app. Setup Code: 906-52-696

Could you please help me ? Before reinstalling, everything was working great. 

Thanks a lot, take care !

**Comment by Seexelas** [comment]
I found this error in the debug logs : 

[29/11/2021, 08:32:48] [DenonTv] Device: 192.168.1.11 AVR Receiver Main Zone, prepare directory and files.
[29/11/2021, 08:32:48] [DenonTv] Device: 192.168.1.11 AVR Receiver Main Zone, save Inputs succesful: [
  {
    "name": "Apple Tv",
    "reference": "MPLAY",
    "mode": "SI"
  },
  {
    "name": "4K Bluray",
    "reference": "BD",
    "mode": "SI"
  }
]
[29/11/2021, 08:32:48] [DenonTv] Device: 192.168.1.11 AVR Receiver Main Zone, requesting Device Info.
[29/11/2021, 08:32:48] [DenonTv] Device: 192.168.1.11 AVR Receiver Main Zone, deviceInfo error: Error: Request failed with status code 403
    at createError (/usr/local/lib/node_modules/homebridge-denon-tv/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/homebridge-denon-tv/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/homebridge-denon-tv/node_modules/axios/lib/adapters/http.js:293:11)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  config: [Object],
  request: [ClientRequest],
  response: [Object],
  isAxiosError: true,
  toJSON: [Function: toJSON]
}, device offline, trying to reconnect
[

**Comment by grzegorz914** [comment]
You miss the port in config

**Comment by Seexelas** [comment]
Thanks, now it's working ! .

During the week end I tried with this config, it was't working. I had a plugin update, maybe this helped.

Many thanks
