### ISSUE TITLE
Issue in 5.1.7

### ISSUE THREAD

**Issue by SaschaRH** [grzegorz914/homebridge-denon-tv#279]
Hi,

after updating to 5.1.7 the following error occurs:
[7.9.2024, 08:14:00] [DenonTv] Device: 192.168.178.55 Marantz, set Input error: TypeError: Cannot read properties of undefined (reading 'name')

Maybe there's something wrong with my config?

Thank you!
Sascha

**Comment by grzegorz914** [comment]
Post the debug please

**Comment by SaschaRH** [comment]
Just updated to 5.1.8:

7.9.2024, 15:41:26] [DenonTv] Device: 192.168.178.55 Marantz, set Input error: TypeError: Cannot read properties of undefined (reading 'name')
[7.9.2024, 15:41:34] [DenonTv] Device: 192.168.178.55 Marantz, Connect Success.
[7.9.2024, 15:41:34] [DenonTv] -------- Marantz --------
[7.9.2024, 15:41:34] [DenonTv] Manufacturer: Marantz
[7.9.2024, 15:41:34] [DenonTv] Model: NR1510
[7.9.2024, 15:41:34] [DenonTv] Zones: 1
[7.9.2024, 15:41:34] [DenonTv] Control: Main Zone
[7.9.2024, 15:41:34] [DenonTv] Firmware: 0
[7.9.2024, 15:41:34] [DenonTv] Api version: 301
[7.9.2024, 15:41:34] [DenonTv] Serialnr:xx
[7.9.2024, 15:41:34] [DenonTv] ----------------------------------
[7.9.2024, 15:41:34] TypeError: Cannot read properties of undefined (reading 'impulseGenerato')
    at MainZone.start (/var/lib/homebridge/node_modules/homebridge-denon-tv/src/mainzone.js:391:34)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at HomebridgeAPI.<anonymous> (/var/lib/homebridge/node_modules/homebridge-denon-tv/index.js:120:8)

**Comment by mtressl** [comment]
same here, again a bugged update.

```
Device: 192.168.1.xxx Denon AVR-3313 Receiver, did finish launching error: TypeError: Cannot read properties of undefined (reading 'impulseGenerato')

/var/lib/homebridge/node_modules/homebridge-denon-tv/src/mainzone.js:391
            await this.openwebif.impulseGenerato.stop();
                                 ^
TypeError: Cannot read properties of undefined (reading 'impulseGenerato')
    at MainZone.start (/var/lib/homebridge/node_modules/homebridge-denon-tv/src/mainzone.js:391:34)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at HomebridgeAPI.<anonymous> (/var/lib/homebridge/node_modules/homebridge-denon-tv/index.js:120:8)
```
