### ISSUE TITLE
Denon TV Child Bridge keeps restarting itself

### ISSUE THREAD

**Issue by HALlowe2000** [grzegorz914/homebridge-denon-tv#282]
The Denon TV child bridge keeps restarting itself over and over and I'm suddenly seeing this error:
```
[9/7/2024, 6:31:38 PM] [homebridge-denon-tv] Device: [redacted] AVR Main, Connect Success.
[9/7/2024, 6:31:38 PM] [homebridge-denon-tv] -------- AVR Main --------
[9/7/2024, 6:31:38 PM] [homebridge-denon-tv] Manufacturer: Denon
[9/7/2024, 6:31:38 PM] [homebridge-denon-tv] Model: AVR-X3400H
[9/7/2024, 6:31:38 PM] [homebridge-denon-tv] Zones: 2
[9/7/2024, 6:31:38 PM] [homebridge-denon-tv] Control: Main Zone
[9/7/2024, 6:31:38 PM] [homebridge-denon-tv] Firmware: 0
[9/7/2024, 6:31:38 PM] [homebridge-denon-tv] Api version: 301
[9/7/2024, 6:31:38 PM] [homebridge-denon-tv] Serialnr: 0005CDF5DEE4
[9/7/2024, 6:31:38 PM] [homebridge-denon-tv] ----------------------------------
[9/7/2024, 6:31:38 PM] [homebridge-denon-tv] Device: [redacted] AVR Main, published as external accessory.
[9/7/2024, 6:31:38 PM] AVR Main 6AB4 is running on port [redacted].
[9/7/2024, 6:31:38 PM] Please add [AVR Main 6AB4] manually in Home app. Setup Code: [redacted]
[9/7/2024, 6:31:38 PM] [homebridge-denon-tv] Device: [redacted] AVR Main, did finish launching error: TypeError: Cannot read properties of undefined (reading 'impulseGenerato')
```
Any ideas? I haven't changed a thing in ages.

**Comment by HALlowe2000** [comment]
Found more entries in the logs:
```
/homebridge/node_modules/homebridge-denon-tv/src/mainzone.js:391
            await this.openwebif.impulseGenerato.stop();
                                 ^
TypeError: Cannot read properties of undefined (reading 'impulseGenerato')
    at MainZone.start (/homebridge/node_modules/homebridge-denon-tv/src/mainzone.js:391:34)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at HomebridgeAPI.<anonymous> (/homebridge/node_modules/homebridge-denon-tv/index.js:120:8)
```

**Comment by christian-lallo** [comment]
Same Problem here.  Plugin keeps restarting.

`9/7/2024, 10:34:28 PM] [DenonTv] Device: 192.168.1.189 AVR X4800h, Connect Success.
[9/7/2024, 10:34:28 PM] [DenonTv] -------- AVR X4800h --------
[9/7/2024, 10:34:28 PM] [DenonTv] Manufacturer: Denon
[9/7/2024, 10:34:28 PM] [DenonTv] Model: AVR-X4800H
[9/7/2024, 10:34:28 PM] [DenonTv] Zones: 3
[9/7/2024, 10:34:28 PM] [DenonTv] Control: Main Zone
[9/7/2024, 10:34:28 PM] [DenonTv] Firmware: 0
[9/7/2024, 10:34:28 PM] [DenonTv] Api version: 301
[9/7/2024, 10:34:28 PM] [DenonTv] Serialnr: 000678A4E900
[9/7/2024, 10:34:28 PM] [DenonTv] ----------------------------------
[INFO] Adding RF Support to device 34ea34433661 with type 279d
[9/7/2024, 10:34:28 PM] [DenonTv] Device: 192.168.1.189 AVR X4800h, published as external accessory.
[9/7/2024, 10:34:28 PM] AVR X4800h A931 is running on port 46378.
[9/7/2024, 10:34:28 PM] Please add [AVR X4800h A931] manually in Home app. Setup Code: 031-45-154
[9/7/2024, 10:34:28 PM] [DenonTv] Device: 192.168.1.189 AVR X4800h, did finish launching error: TypeError: Cannot read properties of undefined (reading 'stop')`

And then Later, the error that causes the plugin crash

`[9/7/2024, 10:35:31 PM] TypeError: Cannot read properties of undefined (reading 'stop')
    at MainZone.start (/volume1/homebridge/node_modules/homebridge-denon-tv/src/mainzone.js:391:46)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at HomebridgeAPI.<anonymous> (/volume1/homebridge/node_modules/homebridge-denon-tv/index.js:120:8)
[`

**Comment by traviswparker** [comment]
There is an "r" missing from the end of impulseGenerator in that line, but another error occurs after fixing it:

```
Error: Start error: Check state error: index is not defined., check again in 15s.
    at MainZone.start (/homebridge/node_modules/homebridge-denon-tv/src/mainzone.js:392:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at HomebridgeAPI.<anonymous> (/homebridge/node_modules/homebridge-denon-tv/index.js:120:8)
```

This release is broken, roll back.

**Comment by HALlowe2000** [comment]
UPDATE: Rolled back to v5.1.7 and things work again. Anything later than 5.1.7 generates that error. 

But the versioning is confusiong to me... Inside Homebridge it says the latest version is 5.1.10, but here on GitHub is says 5.1.5 
![Screen Shot 2024-09-07 at 7 21 38 PM](https://github.com/user-attachments/assets/c386a9f3-2052-48d9-9314-a9a2c524a7f1)

... and when I hit the update button for the plugin in Homebridge... it shows me this:
![Screen Shot 2024-09-07 at 7 23 34 PM](https://github.com/user-attachments/assets/77928948-1d56-4328-846f-ebd6ac2d631e)

So I have no idea what the real version number is or what is going on. 😂 

So... for the sake of this note, the version number it shows me in Homebridge are what I'm referring to. v5.1.7 works, v.5.1.8 - v5.1.10 do not.
