### ISSUE TITLE
error: Cannot read properties of undefined (reading 'value')..

### ISSUE THREAD

**Issue by ValadAmoleo** [grzegorz914/homebridge-denon-tv#285]
Recently started getting this issue: "Denon, did finish launching error: Error: Start error: Connect error: Cannot read properties of undefined (reading 'value').."  It was working perfectly fine up until this week.

Full log from boot to error shown below.  You can see 5 other start fine but the 6th does not.

```shell
[9/12/2024, 9:11:20 PM] [homebridge-denon-tv] Launched child bridge with PID 18160
[9/12/2024, 9:11:20 PM] Registering platform 'homebridge-denon-tv.DenonTv'
[9/12/2024, 9:11:20 PM] [homebridge-denon-tv] Loaded homebridge-denon-tv v5.1.15 child bridge successfully
[9/12/2024, 9:11:20 PM] Loaded 0 cached accessories from cachedAccessories.0EA4E5960AA5.
[9/12/2024, 9:11:20 PM] Homebridge v1.8.4 (HAP v0.12.2) (homebridge-denon-tv) is running on port 36913.
[9/12/2024, 9:11:20 PM] 

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

[9/12/2024, 9:11:21 PM] [homebridge-denon-tv] Device: 192.168.1.232 Cinema Denon, Connect Success.
[9/12/2024, 9:11:21 PM] [homebridge-denon-tv] -------- Cinema Denon --------
[9/12/2024, 9:11:21 PM] [homebridge-denon-tv] Manufacturer: Denon
[9/12/2024, 9:11:21 PM] [homebridge-denon-tv] Model: AVC-X6700H
[9/12/2024, 9:11:21 PM] [homebridge-denon-tv] Zones: 3
[9/12/2024, 9:11:21 PM] [homebridge-denon-tv] Control: Main Zone
[9/12/2024, 9:11:21 PM] [homebridge-denon-tv] Firmware: 0
[9/12/2024, 9:11:21 PM] [homebridge-denon-tv] Api version: 301
[9/12/2024, 9:11:21 PM] [homebridge-denon-tv] Serialnr: 0005CD7F92A0
[9/12/2024, 9:11:21 PM] [homebridge-denon-tv] ----------------------------------
[9/12/2024, 9:11:21 PM] [homebridge-denon-tv] Device: 192.168.1.232 Cinema Denon, published as external accessory.
[9/12/2024, 9:11:21 PM] Cinema Denon EF6E is running on port 52113.
[9/12/2024, 9:11:21 PM] Please add [Cinema Denon EF6E] manually in Home app. Setup Code: 344-45-234
[9/12/2024, 9:11:21 PM] [homebridge-denon-tv] Device: 192.168.1.232 Cinema Denon, Power: OFF
[9/12/2024, 9:11:21 PM] [homebridge-denon-tv] Device: 192.168.1.232 Cinema Denon, Input Name: Cinema Apple TV
[9/12/2024, 9:11:21 PM] [homebridge-denon-tv] Device: 192.168.1.232 Cinema Denon, Reference: DVD
[9/12/2024, 9:11:21 PM] [homebridge-denon-tv] Device: 192.168.1.232 Cinema Denon, Volume: -24dB
[9/12/2024, 9:11:21 PM] [homebridge-denon-tv] Device: 192.168.1.232 Cinema Denon, Mute: ON
[9/12/2024, 9:11:21 PM] [homebridge-denon-tv] Device: 192.168.1.232 Cinema Denon, Volume Control Type: Relative
[9/12/2024, 9:11:21 PM] [homebridge-denon-tv] Device: 192.168.1.232 Cinema Denon, Picture Mode: OFF
[9/12/2024, 9:11:22 PM] [homebridge-denon-tv] Device: 192.168.1.22 Lounge Denon, Connect Success.
[9/12/2024, 9:11:22 PM] [homebridge-denon-tv] -------- Lounge Denon --------
[9/12/2024, 9:11:22 PM] [homebridge-denon-tv] Manufacturer: Denon
[9/12/2024, 9:11:22 PM] [homebridge-denon-tv] Model: *AVR-X4200W
[9/12/2024, 9:11:22 PM] [homebridge-denon-tv] Zones: 3
[9/12/2024, 9:11:22 PM] [homebridge-denon-tv] Control: Main Zone
[9/12/2024, 9:11:22 PM] [homebridge-denon-tv] Firmware: 0
[9/12/2024, 9:11:22 PM] [homebridge-denon-tv] Api version: 300
[9/12/2024, 9:11:22 PM] [homebridge-denon-tv] Serialnr: 0005CD622308
[9/12/2024, 9:11:22 PM] [homebridge-denon-tv] ----------------------------------
[9/12/2024, 9:11:22 PM] [homebridge-denon-tv] Device: 192.168.1.22 Lounge Denon, published as external accessory.
[9/12/2024, 9:11:22 PM] Lounge Denon 0000 is running on port 52114.
[9/12/2024, 9:11:22 PM] Please add [Lounge Denon 0000] manually in Home app. Setup Code: 344-45-234
[9/12/2024, 9:11:22 PM] [homebridge-denon-tv] Device: 192.168.1.22 Lounge Denon, Power: OFF
[9/12/2024, 9:11:22 PM] [homebridge-denon-tv] Device: 192.168.1.22 Lounge Denon, Input Name: AppleTV
[9/12/2024, 9:11:22 PM] [homebridge-denon-tv] Device: 192.168.1.22 Lounge Denon, Reference: SAT/CBL
[9/12/2024, 9:11:22 PM] [homebridge-denon-tv] Device: 192.168.1.22 Lounge Denon, Volume: -43dB
[9/12/2024, 9:11:22 PM] [homebridge-denon-tv] Device: 192.168.1.22 Lounge Denon, Mute: ON
[9/12/2024, 9:11:22 PM] [homebridge-denon-tv] Device: 192.168.1.22 Lounge Denon, Volume Control Type: Relative
[9/12/2024, 9:11:22 PM] [homebridge-denon-tv] Device: 192.168.1.22 Lounge Denon, Picture Mode: OFF
[9/12/2024, 9:11:22 PM] [homebridge-denon-tv] Device: 192.168.1.232 Cinema Denon Surround Mode, Connect Success.
[9/12/2024, 9:11:22 PM] [homebridge-denon-tv] -------- Cinema Denon Surround Mode --------
[9/12/2024, 9:11:22 PM] [homebridge-denon-tv] Manufacturer: Denon
[9/12/2024, 9:11:22 PM] [homebridge-denon-tv] Model: AVC-X6700H
[9/12/2024, 9:11:22 PM] [homebridge-denon-tv] Control: Sound Modes
[9/12/2024, 9:11:22 PM] [homebridge-denon-tv] ----------------------------------
[9/12/2024, 9:11:22 PM] [homebridge-denon-tv] Device: 192.168.1.232 Cinema Denon Surround Mode, published as external accessory.
[9/12/2024, 9:11:22 PM] Cinema Denon Surround Mode 32B4 is running on port 52115.
[9/12/2024, 9:11:22 PM] Please add [Cinema Denon Surround Mode 32B4] manually in Home app. Setup Code: 344-45-234
[9/12/2024, 9:11:22 PM] [homebridge-denon-tv] Device: 192.168.1.232 Cinema Denon Surround Mode, Power: OFF
[9/12/2024, 9:11:22 PM] [homebridge-denon-tv] Device: 192.168.1.232 Cinema Denon Surround Mode, Surround Name: 
[9/12/2024, 9:11:22 PM] [homebridge-denon-tv] Device: 192.168.1.232 Cinema Denon Surround Mode, Reference: 
[9/12/2024, 9:11:22 PM] [homebridge-denon-tv] Device: 192.168.1.232 Cinema Denon Surround Mode, Volume: -24dB
[9/12/2024, 9:11:22 PM] [homebridge-denon-tv] Device: 192.168.1.232 Cinema Denon Surround Mode, Mute: ON
[9/12/2024, 9:11:22 PM] [homebridge-denon-tv] Device: 192.168.1.232 Cinema Denon Surround Mode, Volume Control Type: Relative
[9/12/2024, 9:11:22 PM] [homebridge-denon-tv] Device: 192.168.1.232 Cinema Denon Surround Mode, Picture Mode: OFF
[9/12/2024, 9:11:23 PM] [homebridge-denon-tv] Device: 192.168.1.22 Lounge Denon Surround Mode, Connect Success.
[9/12/2024, 9:11:23 PM] [homebridge-denon-tv] -------- Lounge Denon Surround Mode --------
[9/12/2024, 9:11:23 PM] [homebridge-denon-tv] Manufacturer: Denon
[9/12/2024, 9:11:23 PM] [homebridge-denon-tv] Model: *AVR-X4200W
[9/12/2024, 9:11:23 PM] [homebridge-denon-tv] Control: Sound Modes
[9/12/2024, 9:11:23 PM] [homebridge-denon-tv] ----------------------------------
[9/12/2024, 9:11:23 PM] [homebridge-denon-tv] Device: 192.168.1.22 Lounge Denon Surround Mode, published as external accessory.
[9/12/2024, 9:11:23 PM] Lounge Denon Surround Mode 9F65 is running on port 52116.
[9/12/2024, 9:11:23 PM] Please add [Lounge Denon Surround Mode 9F65] manually in Home app. Setup Code: 344-45-234
[9/12/2024, 9:11:23 PM] [homebridge-denon-tv] Device: 192.168.1.22 Lounge Denon Surround Mode, Power: OFF
[9/12/2024, 9:11:23 PM] [homebridge-denon-tv] Device: 192.168.1.22 Lounge Denon Surround Mode, Surround Name: 
[9/12/2024, 9:11:23 PM] [homebridge-denon-tv] Device: 192.168.1.22 Lounge Denon Surround Mode, Reference: 
[9/12/2024, 9:11:23 PM] [homebridge-denon-tv] Device: 192.168.1.22 Lounge Denon Surround Mode, Volume: -43dB
[9/12/2024, 9:11:23 PM] [homebridge-denon-tv] Device: 192.168.1.22 Lounge Denon Surround Mode, Mute: ON
[9/12/2024, 9:11:23 PM] [homebridge-denon-tv] Device: 192.168.1.22 Lounge Denon Surround Mode, Volume Control Type: Relative
[9/12/2024, 9:11:23 PM] [homebridge-denon-tv] Device: 192.168.1.22 Lounge Denon Surround Mode, Picture Mode: OFF
[9/12/2024, 9:11:24 PM] [homebridge-denon-tv] Device: 192.168.1.232 Cinema Denon Zone 2, Connect Success.
[9/12/2024, 9:11:24 PM] [homebridge-denon-tv] -------- Cinema Denon Zone 2 --------
[9/12/2024, 9:11:24 PM] [homebridge-denon-tv] Manufacturer: Denon
[9/12/2024, 9:11:24 PM] [homebridge-denon-tv] Model: AVC-X6700H
[9/12/2024, 9:11:24 PM] [homebridge-denon-tv] Control: Zone 2
[9/12/2024, 9:11:24 PM] [homebridge-denon-tv] ----------------------------------
[9/12/2024, 9:11:24 PM] [homebridge-denon-tv] Device: 192.168.1.232 Cinema Denon Zone 2, published as external accessory.
[9/12/2024, 9:11:24 PM] Cinema Denon Zone 2 2813 is running on port 52117.
[9/12/2024, 9:11:24 PM] Please add [Cinema Denon Zone 2 2813] manually in Home app. Setup Code: 344-45-234
[9/12/2024, 9:11:24 PM] [homebridge-denon-tv] Device: 192.168.1.232 Cinema Denon Zone 2, Power: OFF
[9/12/2024, 9:11:24 PM] [homebridge-denon-tv] Device: 192.168.1.232 Cinema Denon Zone 2, Input Name: CD
[9/12/2024, 9:11:24 PM] [homebridge-denon-tv] Device: 192.168.1.232 Cinema Denon Zone 2, Reference: CD
[9/12/2024, 9:11:24 PM] [homebridge-denon-tv] Device: 192.168.1.232 Cinema Denon Zone 2, Volume: -40dB
[9/12/2024, 9:11:24 PM] [homebridge-denon-tv] Device: 192.168.1.232 Cinema Denon Zone 2, Mute: ON
[9/12/2024, 9:11:24 PM] [homebridge-denon-tv] Device: 192.168.1.232 Cinema Denon Zone 2, Volume Control Type: Relative
[9/12/2024, 9:11:24 PM] [homebridge-denon-tv] Device: 192.168.1.232 Cinema Denon Zone 2, Picture Mode: OFF
[9/12/2024, 9:11:24 PM] [homebridge-denon-tv] Device: 192.168.1.53 Lounge Rumble Denon, did finish launching.
[9/12/2024, 9:11:24 PM] [homebridge-denon-tv] Device: 192.168.1.53 Lounge Rumble Denon, Config: {
  "name": "Lounge Rumble Denon",
  "host": "192.168.1.53",
  "port": 80,
  "generation": 0,
  "zoneControl": 0,
  "getInputsFromDevice": false,
  "getFavoritesFromDevice": false,
  "getQuickSmartSelectFromDevice": false,
  "inputsDisplayOrder": 0,
  "inputs": [
    {
      "name": "Rumble",
      "reference": "CD"
    }
  ],
  "sensorPower": false,
  "sensorVolume": false,
  "sensorMute": false,
  "sensorInput": false,
  "infoButtonCommand": "MNMEN ON",
  "masterPower": false,
  "masterMute": false,
  "masterVolume": false,
  "volumeControlNamePrefix": false,
  "volumeControl": 2,
  "volumeMax": 100,
  "refreshInterval": 5,
  "enableDebugMode": true,
  "disableLogInfo": false,
  "disableLogDeviceInfo": false,
  "disableLogConnectError": false,
  "restFul": {
    "enable": false,
    "debug": false
  },
  "mqtt": {
    "enable": false,
    "debug": false,
    "auth": false,
    "passwd": "removed"
  }
}
[9/12/2024, 9:11:24 PM] [homebridge-denon-tv] Device: 192.168.1.53 Lounge Rumble Denon, debug: Connect data: {
  "FriendlyName": {
    "value": "DENON AVR-2113"
  },
  "Power": {
    "value": "STANDBY"
  },
  "ZonePower": {
    "value": "OFF"
  },
  "RenameZone": {
    "value": "MAIN ZONE"
  },
  "TopMenuLink": {
    "value": "OFF"
  },
  "ModelId": {
    "value": 4
  },
  "SalesArea": {
    "value": 1
  },
  "InputFuncSelect": {
    "value": "RUMBLE"
  },
  "NetFuncSelect": {
    "value": "RHAPSODY"
  },
  "selectSurround": {
    "value": "PURE DIRECT"
  },
  "VolumeDisplay": {
    "value": "Relative"
  },
  "MasterVolume": {
    "value": 12
  },
  "Mute": {
    "value": "off"
  },
  "RemoteMaintenance": {
    "value": "OFF"
  },
  "SubwooferDisplay": {
    "value": "FALSE"
  },
  "Zone2VolDisp": {
    "value": "TRUE"
  },
  "LastfmDisplay": {
    "value": "FALSE"
  }
}
[9/12/2024, 9:11:24 PM] [homebridge-denon-tv] Device: 192.168.1.53 Lounge Rumble Denon, debug: Saved data: {
  "FriendlyName": {
    "value": "DENON AVR-2113"
  },
  "Power": {
    "value": "STANDBY"
  },
  "ZonePower": {
    "value": "OFF"
  },
  "RenameZone": {
    "value": "MAIN ZONE"
  },
  "TopMenuLink": {
    "value": "OFF"
  },
  "ModelId": {
    "value": 4
  },
  "SalesArea": {
    "value": 1
  },
  "InputFuncSelect": {
    "value": "RUMBLE"
  },
  "NetFuncSelect": {
    "value": "RHAPSODY"
  },
  "selectSurround": {
    "value": "PURE DIRECT"
  },
  "VolumeDisplay": {
    "value": "Relative"
  },
  "MasterVolume": {
    "value": 12
  },
  "Mute": {
    "value": "off"
  },
  "RemoteMaintenance": {
    "value": "OFF"
  },
  "SubwooferDisplay": {
    "value": "FALSE"
  },
  "Zone2VolDisp": {
    "value": "TRUE"
  },
  "LastfmDisplay": {
    "value": "FALSE"
  }
}
[9/12/2024, 9:11:24 PM] [homebridge-denon-tv] Device: 192.168.1.53 Lounge Rumble Denon, did finish launching error: Error: Start error: Connect error: Cannot read properties of undefined (reading 'value')..
/var/lib/homebridge/node_modules/@francoisdebellescize/homebridge-sure-petcare-platform/node_modules/@francoisdebellescize/sure_petcare/dist/lib.js:131
                callback(body);
                ^
TypeError: acc.pollStatus is not a function
    at /var/lib/homebridge/node_modules/@francoisdebellescize/homebridge-sure-petcare-platform/index.js:75:15
    at /var/lib/homebridge/node_modules/@francoisdebellescize/homebridge-sure-petcare-platform/node_modules/@francoisdebellescize/sure_petcare/dist/lib.js:103:17
    at Request._callback (/var/lib/homebridge/node_modules/@francoisdebellescize/homebridge-sure-petcare-platform/node_modules/@francoisdebellescize/sure_petcare/dist/lib.js:131:17)
    at Request.self.callback (/var/lib/homebridge/node_modules/@francoisdebellescize/homebridge-sure-petcare-platform/node_modules/request/request.js:185:22)
    at Request.emit (node:events:519:28)
    at Request.<anonymous> (/var/lib/homebridge/node_modules/@francoisdebellescize/homebridge-sure-petcare-platform/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:519:28)
    at IncomingMessage.<anonymous> (/var/lib/homebridge/node_modules/@francoisdebellescize/homebridge-sure-petcare-platform/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:633:28)
    at IncomingMessage.emit (node:events:531:35)

```

**Comment by ValadAmoleo** [comment]
Hang on, that's strange.  Why is that surfacing an error from a different plugin at the bottom when this is supposed to be just the logs for Denon TV.  That other plugin (sure-petcare-platform) is working fine.

**Comment by grzegorz914** [comment]
Fixed, update to latest version and let me know.

**Comment by ValadAmoleo** [comment]
Thanks for fixing this.
