### ISSUE TITLE
Plugin restarts with `address already in use`

### ISSUE THREAD

**Issue by danwelcome** [grzegorz914/homebridge-denon-tv#298]
This seemed to start happening within the last month or so. I run homebridge in a container and have tried restarting it multiple times.  I'm not sure what else would be bound to this port.

Here are the debug logs:
```
[11/8/2024, 3:22:37 PM] [homebridge-denon-tv] Restarting Process...
[11/8/2024, 3:22:38 PM] [homebridge-denon-tv] Launched child bridge with PID 18233
[11/8/2024, 3:22:39 PM] Registering platform 'homebridge-denon-tv.DenonTv'
[11/8/2024, 3:22:39 PM] [homebridge-denon-tv] Loaded homebridge-denon-tv v5.1.25 child bridge successfully
[11/8/2024, 3:22:39 PM] Loaded 0 cached accessories from cachedAccessories.0EE253D55332.
[11/8/2024, 3:22:39 PM] [homebridge-denon-tv] Device: 192.168.1.8 Denon, debug: Did finish launching.
[11/8/2024, 3:22:39 PM] [homebridge-denon-tv] Device: 192.168.1.8 Denon, Config: {
  "name": "Denon",
  "host": "192.168.1.8",
  "port": 8080,
  "generation": 2,
  "zoneControl": 0,
  "getInputsFromDevice": true,
  "getFavoritesFromDevice": false,
  "getQuickSmartSelectFromDevice": false,
  "inputsDisplayOrder": 0,
  "inputs": [
    {
      "name": "Apple TV Again",
      "reference": "SAT/CBL"
    },
    {
      "name": "Chromecast",
      "reference": "MPLAY"
    },
    {
      "name": "PS5",
      "reference": "GAME"
    },
    {
      "name": "Switch",
      "reference": "AUX1"
    },
    {
      "name": "Steam Deck",
      "reference": "AUX2"
    },
    {
      "name": "TV Audio",
      "reference": "TV"
    }
  ],
  "buttons": [
    {
      "displayType": 0
    }
  ],
  "buttonsZ2": [
    {
      "displayType": 0
    }
  ],
  "buttonsZ3": [
    {
      "displayType": 0
    }
  ],
  "sensorPower": false,
  "sensorVolume": false,
  "sensorMute": false,
  "sensorInput": false,
  "sensorSurrounds": [
    {
      "displayType": 0
    }
  ],
  "infoButtonCommand": "MNMEN ON",
  "masterPower": false,
  "masterMute": false,
  "masterVolume": false,
  "volumeControlNamePrefix": false,
  "volumeControl": 0,
  "volumeMax": 100,
  "refreshInterval": 5,
  "enableDebugMode": true,
  "disableLogInfo": false,
  "disableLogDeviceInfo": false,
  "disableLogConnectError": false,
  "restFul": {
    "enable": false,
    "debug": false
  },
  "mqtt": {
    "enable": false,
    "debug": false,
    "auth": false,
    "passwd": "removed"
  }
}
[11/8/2024, 3:22:39 PM] [homebridge-denon-tv] Device: 192.168.1.8 Denon, Start impulse generator started.
Error: listen EADDRINUSE: address already in use :::43359
    at Server.setupListenHandle [as _listen2] (node:net:1904:16)
    at listenInCluster (node:net:1961:12)
    at Server.listen (node:net:2063:7)
    at EventedHTTPServer.listen (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:164:20)
    at HAPServer.listen (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:377:21)
    at Bridge.<anonymous> (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1368:18)
    at step (/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:195:27)
    at Object.next (/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:176:57)
    at /homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
[11/8/2024, 3:22:39 PM] [homebridge-denon-tv] Child bridge process ended
[11/8/2024, 3:22:39 PM] [homebridge-denon-tv] Process Ended. Code: 1, Signal: null
```

**Comment by grzegorz914** [comment]
Try to change bridge port in config.json

**Comment by danwelcome** [comment]
That did the trick! Thanks!
