### ISSUE TITLE
TypeError: Cannot read property 'item' of null

### ISSUE THREAD

**Issue by jsilarow** [grzegorz914/homebridge-denon-tv#3]
Hi Grzegorz.
I'm having problems with the latest version (1.1.70).

Environment:
Homebridge version 0.4.50 
installed on Raspberry PI W zero; 
System Raspbian 10.
Node.js Version | v13.6.0
Npm Versionv6.13.7

Denon-TV plugin configured properly:
in Platforms:

`{
            "devices": [
                {
                    "name": "Denon",
                    "host": "192.168.1.102",
                    "port": 8080,
                    "switchInfoMenu": true,
                    "inputs": [
                        {
                            "name": "Xbox",
                            "reference": "Game"
                        },
                        {
                            "name": "AppleTV",
                            "reference": "Media Player"
                        },
                        {
                            "name": "TV",
                            "reference": "CBL/SAT"
                        },
                        {
                            "name": "TV Audio",
                            "reference": "TV Audio"
                        }
                    ]
                }
            ],
            "platform": "DenonTv"
        }` 
From Logs I can read that there is someting with `getPowerState(callback)` and `getInput(callback)` on index.js file.

In my opinion, parsing XML of status from my device is failing.
The XML it selfs contains (http://192.168.1.102/goform/formMainZone_MainZoneXmlStatusLite.xml):

`<item>
<Power>
<value>OFF</value>
</Power>
<InputFuncSelect>
<value>TV</value>
</InputFuncSelect>
<VolumeDisplay>
<value>Absolute</value>
</VolumeDisplay>
<MasterVolume>
<value>-55.0</value>
</MasterVolume>
<Mute>
<value>off</value>
</Mute>
</item>`

THE ERRORS I'm getting are:

`[2/23/2020, 2:06:28 PM] TypeError: Cannot read property 'item' of null
    at /usr/local/lib/node_modules/homebridge-denon-tv/index.js:284:26
    at Parser.<anonymous> (/usr/local/lib/node_modules/homebridge-denon-tv/node_modules/xml2js/lib/parser.js:304:18)
    at Parser.emit (events.js:321:20)
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/homebridge-denon-tv/node_modules/xml2js/lib/parser.js:314:16)
    at Parser.parseString (/usr/local/lib/node_modules/homebridge-denon-tv/node_modules/xml2js/lib/parser.js:5:59)
    at exports.parseString (/usr/local/lib/node_modules/homebridge-denon-tv/node_modules/xml2js/lib/parser.js:369:19)
    at Request._callback (/usr/local/lib/node_modules/homebridge-denon-tv/index.js:283:51)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-denon-tv/node_modules/request/request.js:185:22)
    at Request.emit (events.js:321:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-denon-tv/node_modules/request/request.js:1154:10)
[2/23/2020, 2:06:28 PM] TypeError: Cannot read property 'item' of null
    at /usr/local/lib/node_modules/homebridge-denon-tv/index.js:379:34
    at Parser.<anonymous> (/usr/local/lib/node_modules/homebridge-denon-tv/node_modules/xml2js/lib/parser.js:304:18)
    at Parser.emit (events.js:321:20)
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/homebridge-denon-tv/node_modules/xml2js/lib/parser.js:314:16)
    at Parser.parseString (/usr/local/lib/node_modules/homebridge-denon-tv/node_modules/xml2js/lib/parser.js:5:59)
    at exports.parseString (/usr/local/lib/node_modules/homebridge-denon-tv/node_modules/xml2js/lib/parser.js:369:19)
    at Request._callback (/usr/local/lib/node_modules/homebridge-denon-tv/index.js:378:51)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-denon-tv/node_modules/request/request.js:185:22)
    at Request.emit (events.js:321:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-denon-tv/node_modules/request/request.js:1154:10)
[2/23/2020, 2:06:28 PM] Got SIGTERM, shutting down Homebridge...`

and:

`[2/23/2020, 2:07:18 PM] TypeError: Cannot read property 'item' of null
    at /usr/local/lib/node_modules/homebridge-denon-tv/index.js:379:34
    at Parser.<anonymous> (/usr/local/lib/node_modules/homebridge-denon-tv/node_modules/xml2js/lib/parser.js:304:18)
    at Parser.emit (events.js:321:20)
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/homebridge-denon-tv/node_modules/xml2js/lib/parser.js:314:16)
    at Parser.parseString (/usr/local/lib/node_modules/homebridge-denon-tv/node_modules/xml2js/lib/parser.js:5:59)
    at exports.parseString (/usr/local/lib/node_modules/homebridge-denon-tv/node_modules/xml2js/lib/parser.js:369:19)
    at Request._callback (/usr/local/lib/node_modules/homebridge-denon-tv/index.js:378:51)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-denon-tv/node_modules/request/request.js:185:22)
    at Request.emit (events.js:321:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-denon-tv/node_modules/request/request.js:1154:10)
[2/23/2020, 2:07:18 PM] TypeError: Cannot read property 'item' of null
    at /usr/local/lib/node_modules/homebridge-denon-tv/index.js:284:26
    at Parser.<anonymous> (/usr/local/lib/node_modules/homebridge-denon-tv/node_modules/xml2js/lib/parser.js:304:18)
    at Parser.emit (events.js:321:20)
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/homebridge-denon-tv/node_modules/xml2js/lib/parser.js:314:16)
    at Parser.parseString (/usr/local/lib/node_modules/homebridge-denon-tv/node_modules/xml2js/lib/parser.js:5:59)
    at exports.parseString (/usr/local/lib/node_modules/homebridge-denon-tv/node_modules/xml2js/lib/parser.js:369:19)
    at Request._callback (/usr/local/lib/node_modules/homebridge-denon-tv/index.js:283:51)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-denon-tv/node_modules/request/request.js:185:22)
    at Request.emit (events.js:321:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-denon-tv/node_modules/request/request.js:1154:10)
[2/23/2020, 2:07:18 PM] Got SIGTERM, shutting down Homebridge...`

**Comment by grzegorz914** [comment]
Please make update to 1.1.71 and check again.

**Comment by jsilarow** [comment]
Hi, I've tested version 1.1.71 and as soon as I've added manually Denon to Home app on my iPhone, I've got this crash on the Homebridge:

`[2/23/2020, 8:24:43 PM] TypeError: Cannot read property 'item' of null
    at /usr/local/lib/node_modules/homebridge-denon-tv/index.js:284:26
    at Parser.<anonymous> (/usr/local/lib/node_modules/homebridge-denon-tv/node_modules/xml2js/lib/parser.js:304:18)
    at Parser.emit (events.js:321:20)
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/homebridge-denon-tv/node_modules/xml2js/lib/parser.js:314:16)
    at Parser.parseString (/usr/local/lib/node_modules/homebridge-denon-tv/node_modules/xml2js/lib/parser.js:5:59)
    at exports.parseString (/usr/local/lib/node_modules/homebridge-denon-tv/node_modules/xml2js/lib/parser.js:369:19)
    at Request._callback (/usr/local/lib/node_modules/homebridge-denon-tv/index.js:283:18)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-denon-tv/node_modules/request/request.js:185:22)
    at Request.emit (events.js:321:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-denon-tv/node_modules/request/request.js:1154:10)
[2/23/2020, 8:24:43 PM] TypeError: Cannot read property 'item' of null
    at /usr/local/lib/node_modules/homebridge-denon-tv/index.js:379:34
    at Parser.<anonymous> (/usr/local/lib/node_modules/homebridge-denon-tv/node_modules/xml2js/lib/parser.js:304:18)
    at Parser.emit (events.js:321:20)
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/homebridge-denon-tv/node_modules/xml2js/lib/parser.js:314:16)
    at Parser.parseString (/usr/local/lib/node_modules/homebridge-denon-tv/node_modules/xml2js/lib/parser.js:5:59)
    at exports.parseString (/usr/local/lib/node_modules/homebridge-denon-tv/node_modules/xml2js/lib/parser.js:369:19)
    at Request._callback (/usr/local/lib/node_modules/homebridge-denon-tv/index.js:378:18)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-denon-tv/node_modules/request/request.js:185:22)
    at Request.emit (events.js:321:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-denon-tv/node_modules/request/request.js:1154:10)
[2/23/2020, 8:24:43 PM] Got SIGTERM, shutting down Homebridge...
[2/23/2020, 8:24:48 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[2/23/2020, 8:24:53 PM] [HB Supervisor] Restarting Homebridge...
[2/23/2020, 8:24:53 PM] [HB Supervisor] Started Homebridge with PID: 5525`

**Comment by grzegorz914** [comment]
What a device U use?

**Comment by jsilarow** [comment]
AVR-X1300W

**Comment by grzegorz914** [comment]
Get me output from:
IP:8080/goform/formMainZone_MainZoneXmlStatusLite.xml

**Comment by jsilarow** [comment]
actually I posted it in the first post:
`<item>
<Power>
<value>ON</value>
</Power>
<InputFuncSelect>
<value>TV</value>
</InputFuncSelect>
<VolumeDisplay>
<value>Absolute</value>
</VolumeDisplay>
<MasterVolume>
<value>-55.0</value>
</MasterVolume>
<Mute>
<value>off</value>
</Mute>
</item>`

BTW it's on :80 not :8080 port

**Comment by grzegorz914** [comment]
Please change the port to 80 in Your config.
