### ISSUE TITLE
Lots of ETIMEDOUT errors

### ISSUE THREAD

**Issue by vincedarley** [grzegorz914/homebridge-denon-tv#38]
A few days ago I updated, and now get these errors logged every second (so thousands and thousands of them!). Is this a problem with my Denon (which seems to be working just fine) or something has changed with this nice plugin? Other devices on homebridge are working just fine.

[9/9/2020, 2:17:17 PM] [DenonTv] Device: 192.168.1.93 Zone 2, getDeviceInfo eror: Error: read ETIMEDOUT
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'read',
  config: [Object],
  request: [Writable],
  response: undefined,
  isAxiosError: true,
  toJSON: [Function]
}, state: Offline
[9/9/2020, 2:17:17 PM] [DenonTv] Device: 192.168.1.93 Zone 1, getDeviceInfo eror: Error: read ETIMEDOUT
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'read',
  config: [Object],
  request: [Writable],
  response: undefined,
  isAxiosError: true,
  toJSON: [Function]
}, state: Offline
[9/9/2020, 2:17:20 PM] [DenonTv] Device: 192.168.1.93 Zone 1, getDeviceInfo eror: Error: read ETIMEDOUT
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'read',
  config: [Object],
  request: [Writable],
  response: undefined,
  isAxiosError: true,
  toJSON: [Function]
}, state: Offli

**Comment by grzegorz914** [comment]
Please try update to The latest version and report again.

**Comment by vincedarley** [comment]
Hi - this is with 3.2.0 - the latest version I can see. Vince.

**Comment by grzegorz914** [comment]
I have checked this and all working OK on my site, can U ping the Receiver, is the receiver available in HomeKit.app, can U operate the receiver with original Denon.app?

**Comment by vincedarley** [comment]
The Denon app does (and did) seem to work ok.

I installed the just-released 3.3.0, and rebooted everything, including
unplugging the Denon and its network cable, and now everything works ok.
Not sure quite where the problem was. But thank you.

>

**Comment by grzegorz914** [comment]
Ok, now is completely moved to Async/await.
