### ISSUE TITLE
Unable to Select Input

### ISSUE THREAD

**Issue by andywmcrae** [grzegorz914/homebridge-denon-tv#4]
I can power on and off.  If I select a input, I get this:

[Homebridge] [2/25/2020, 2:34:05 PM] [DenonTv] Device: 192.168.10.44, set new Input successfull: function() {
    if (called) {
      throw new Error("This callback function has already been called by someone else; it can only be called one time.");
    }
    else {
      called = true;
      return func.apply(this, arguments);
    }
  }
[Homebridge] [2/25/2020, 2:34:05 PM] TypeError: callback is not a function
    at Request._callback (/home/hoobs/.hoobs/node_modules/homebridge-denon-tv/index.js:439:6)
    at Request.self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
    at Request.emit (events.js:223:5)
    at Request.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:223:5)
    at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:312:28)
    at IncomingMessage.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
[Homebridge] [2/25/2020, 2:34:05 PM] Got SIGTERM, shutting down service...

This is my code:  

        {
            "platform": "DenonTv",
            "plugin_map": {
                "plugin_name": "homebridge-denon-tv"
            },
            "devices": [
                {
                    "name": "DenDenon",
                    "host": "192.168.XX.XX",
                    "port": 8080,
                    "switchInfoMenu": true,
                    "inputs": [
                        {
                            "name": "Apple TV",
                            "reference": "GAME"
                        },
                        {
                            "name": "Blu-ray",
                            "reference": "BD"
                        },
                        {
                            "name": "DirecTV",
                            "reference": "SAT/CBL"
                        },
                        {
                            "name": "Roku",
                            "reference": "MPLAY"
                        }
                    ]
                }
            ]
        }

**Comment by grzegorz914** [comment]
Fixed
