### ISSUE TITLE
get deviceinfo error 

### ISSUE THREAD

**Issue by lordchris78** [grzegorz914/homebridge-denon-tv#44]
Device 192.168.x.x Receiver, getDeviceInfo parse string error: TypeError: Cannot read property 'BrandCode' of undefined
    at denonTvDevice.getDeviceInfo (/homebridge/node_modules/homebridge-denon-tv/index.js:341:63)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

I have receiver AVR-4311.

**Comment by grzegorz914** [comment]
Update and try again

**Comment by jorikcaljouw** [comment]
I think I have the same problem. I have a Marantz NR1602 and even after this update I still get:

```[10/7/2020, 8:19:23 PM] [DenonTv] Device: 192.168.1.11 Marantz Main Zone, get current Power state successful: ON
[10/7/2020, 8:19:23 PM] [DenonTv] Device: 192.168.1.11 Marantz Main Zone, get current Input successful: Apple TV SAT
[10/7/2020, 8:19:23 PM] [DenonTv] Device: 192.168.1.11 Marantz Main Zone, get current Mute state successful: OFF
[10/7/2020, 8:19:23 PM] [DenonTv] Device: 192.168.1.11 Marantz Main Zone, get current Volume level successful: -29 dB
[10/7/2020, 8:19:30 PM] [DenonTv] Device: 192.168.1.11 Marantz Main Zone, state: Online.
[10/7/2020, 8:19:30 PM] [DenonTv] Device 192.168.1.11 Marantz, getDeviceInfo parse string error: TypeError: Cannot read property 'BrandCode' of undefined
    at denonTvDevice.getDeviceInfo (/opt/nodejs/lib/node_modules/homebridge-denon-tv/index.js:341:63)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

But I think my device is too old because if I try to open http://192.168.1.11/goform/Deviceinfo.xml, I see:
```
Access Error: Data follows

Form Deviceinfo.xml is not defined
```

So I guess `result.Device_Info` is already undefined and hence the check should first check if `result.Device_Info` is not undefined before checking `BrandCode`?

**Comment by lordchris78** [comment]
Sorry still the same problem.

[10/7/2020, 8:27:13 PM] [DenonTv] Device: 192.168.x.xx Receiver Main Zone, state: Online.
[10/7/2020, 8:27:13 PM] [DenonTv] Device 192.168.x.xx Receiver, getDeviceInfo parse string error: TypeError: Cannot read property 'BrandCode' of undefined
    at denonTvDevice.getDeviceInfo (/homebridge/node_modules/homebridge-denon-tv/index.js:341:35)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by jorikcaljouw** [comment]
I'll submit a PR, I made a small change and it seems to work for me now

**Comment by grzegorz914** [comment]
The devices are to old to get deviceInfo from api but I create some fix tomorrow to prevent this error.

**Comment by lordchris78** [comment]
Thanks for the fix :)
