### ISSUE TITLE
Denon, getDeviceInfo eror: Error: Request failed with status code 403

### ISSUE THREAD

**Issue by newt10** [grzegorz914/homebridge-denon-tv#56]
```
0|homebridge  | [12/26/2020, 7:16:42 PM] [DenonTv] Device: XX.XX.XX.XX Denon, getDeviceInfo eror: Error: Request failed with status code 403
0|homebridge  |     at createError (/home/pi/.nvm/versions/node/v12.16.1/lib/node_modules/homebridge-denon-tv/node_modules/axios/lib/core/createError.js:16:15)
0|homebridge  |     at settle (/home/pi/.nvm/versions/node/v12.16.1/lib/node_modules/homebridge-denon-tv/node_modules/axios/lib/core/settle.js:17:12)
0|homebridge  |     at IncomingMessage.handleStreamEnd (/home/pi/.nvm/versions/node/v12.16.1/lib/node_modules/homebridge-denon-tv/node_modules/axios/lib/adapters/http.js:260:11)
0|homebridge  |     at IncomingMessage.emit (events.js:323:22)
0|homebridge  |     at endReadableNT (_stream_readable.js:1204:12)
0|homebridge  |     at processTicksAndRejections (internal/process/task_queues.js:84:21)
0|homebridge  |  {
0|homebridge  |   config: [Object],
0|homebridge  |   request: [ClientRequest],
0|homebridge  |   response: [Object],
0|homebridge  |   isAxiosError: true,
0|homebridge  |   toJSON: [Function: toJSON]
0|homebridge  | }, state: Offline
```

**Config**

```
{
            "devices": [
                {
                    "name": "Denon",
                    "host": "XX.XX.XX.XX",
                    "port": 80,
                    "refreshInterval": 5,
                    "zoneControl": 0,
                    "volumeControl": 1,
                    "masterPower": false,
                    "switchInfoMenu": false,
                    "inputs": [
                        {
                            "name": "DVD",
                            "reference": "DVD",
                            "type": "HDMI",
                            "mode": "SI"
                        }
                    ],
                    "manufacturer": "Denon",
                    "modelName": "S750H"
                }
            ],
            "platform": "DenonTv"
        }
```

**Comment by newt10** [comment]
I was able to fix this by using 8080 as the port
