### ISSUE TITLE
Cannot read property BrandCode

### ISSUE THREAD

**Issue by lzparkma** [grzegorz914/homebridge-denon-tv#73]
Am getting issue with Marantz NR1602. Looks likes same behaviour as #44.

**Comment by grzegorz914** [comment]
Try update and get feedback

**Comment by lzparkma** [comment]
Thanks for the update but still have issue with 3.7.11 under Homebridge v1.3.0. Let me know if there is any debug/logs needed to help.

`[2/23/2021, 12:30:29 AM] [homebridge-denon-tv] Device: 10.0.0.43 Source, Device Info eror: TypeError: Cannot read property 'BrandCode' of undefined
    at denonTvDevice.getDeviceInfo (/homebridge/node_modules/homebridge-denon-tv/index.js:161:64)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5), state: Offline, trying to reconnect`

**Comment by grzegorz914** [comment]
Try update again

**Comment by lzparkma** [comment]
Fixed. Thanks for the quick response.
