### ISSUE TITLE
'Active Identifier': characteristic was supplied illegal value: number -1 exceeded minimum of 0

### ISSUE THREAD

**Issue by zackva** [grzegorz914/homebridge-denon-tv#77]
Hi,

I'm running homebridge v1.3.1 in docker container and receiving this error

```
[2/27/2021, 10:39:08 PM] [homebridge-denon-tv] This plugin generated a warning from the characteristic 'Active Identifier': characteristic was supplied illegal value: number -1 exceeded minimum of 0. See https://git.io/JtMGR for more info.
[2/27/2021, 10:39:08 PM] [homebridge-denon-tv] Error: 
    at ActiveIdentifier.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2164:105)
    at ActiveIdentifier.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2114:14)
    at ActiveIdentifier.Characteristic.updateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1365:20)
    at Television.Service.updateCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:465:35)
    at denonTvDevice.getDeviceState (/homebridge/node_modules/homebridge-denon-tv/index.js:231:25)
    at /homebridge/node_modules/homebridge-denon-tv/index.js:150:11
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[2/27/2021, 10:39:08 PM] [DenonTv] Device: 192.168.0.149 Perseverance Main Zone, get current Input successful: undefined TV
[2/27/2021, 10:39:08 PM] [DenonTv] Device: 192.168.0.149 Perseverance Main Zone, get current Mute state: ON
[2/27/2021, 10:39:08 PM] [DenonTv] Device: 192.168.0.149 Perseverance Main Zone, get current Volume level: -23 dB 
[2/27/2021, 10:39:08 PM] [DenonTv] Device 192.168.0.149 Perseverance Main Zone, get device status data: {
  "item": {
    "Power": [
        "value": [
          "OFF"
        ]
      }
    ],
    "InputFuncSelect": [
      {
        "value": [
          "TV"
        ]
      }
    ],
    "VolumeDisplay": [
        "value": [
          "Absolute"
        ]
      }
    ],
    "MasterVolume": [
      {
        "value": [
          "-23.5"
        ]
      }
    ],
    "Mute": [
      {
        "value": [
          "off"
        ]
      }
    ]
  }
}
```

Please let me know if there's any other info I can provide.

Thank you!

**Comment by grzegorz914** [comment]
Please add input „TV” to Your config

**Comment by grzegorz914** [comment]
Fixed
