### ISSUE TITLE
update Device state error: TypeError: Cannot read property '0' of undefined in 3.8.0beta5

### ISSUE THREAD

**Issue by axelweichert** [grzegorz914/homebridge-denon-tv#80]
Hi,

the beta releases seems to be published for everyone, i think.

After installing one of the 3.8.0 betas i get the following error message running on homebridge 1.3.1:

[01/03/2021, 07:52:38] [DenonTv] Manufacturer: Denon
[01/03/2021, 07:52:38] [DenonTv] Model: AVR-X1600H
[01/03/2021, 07:52:38] [DenonTv] Zones: 2
[01/03/2021, 07:52:38] [DenonTv] Api version: 0301
[01/03/2021, 07:52:38] [DenonTv] Serialnr: XXXXXXXXXX
[01/03/2021, 07:52:38] [DenonTv] Firmware: 00
[01/03/2021, 07:52:38] [DenonTv] ----------------------------------
[01/03/2021, 07:52:38] [DenonTv] Device: 192.168.1.116 Denon X1600H Main Zone, update Device state error: TypeError: Cannot read property '0' of undefined
    at denonTvDevice.prepareAccessory (/usr/local/lib/node_modules/homebridge-denon-tv/index.js:757:72)
    at denonTvDevice.updateDeviceState (/usr/local/lib/node_modules/homebridge-denon-tv/index.js:263:10)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by chetstone** [comment]
Why was this closed? 
I just upgraded from 3.4 to 3.10.30 and I'm getting.

```
TypeError: Cannot read property '0' of undefined
    at denonTvDevice.prepareAccessory (/opt/homebrew/lib/node_modules/homebridge-denon-tv/index.js:290:78)
```
I wonder if something in my  config.json  incompatible with the new version? 

```
         {
            "devices": [
                {
                    "name": "Receiver Main",
                    "host": "192.168.1.143",
                    "port": 80,
                    "refreshInterval": 5,
                    "zoneControl": 0,
                    "volumeControl": 1,
                    "masterPower": true,
                    "switchInfoMenu": false,
                    "inputs": [
                        {
                            "name": "Apple TV Music",
                            "reference": "DVD",
                            "type": "OTHER",
                            "mode": "SI"
                        },
                        {
                            "name": "TV",
                            "reference": "TV",
                            "type": "OTHER",
                            "mode": "SI"
                        },
                        {
                            "name": "Computer",
                            "reference": "CD",
                            "type": "OTHER",
                            "mode": "SI"
                        },
                      {
                            "name": "Gesar",
                            "reference": "DVR",
                            "type": "OTHER",
                            "mode": "SI"
                        },
                        {
                            "name": "MOVIE",
                            "reference": "MOVIE",
                            "type": "OTHER",
                            "mode": "MS"
                        },
                        {
                            "name": "Stereo",
                            "reference": "STEREO",
                            "type": "OTHER",
                            "mode": "MS"
                        },
                        {
                            "name": "Quick 4",
                            "reference": "QUICK4",
                            "type": "OTHER",
                            "mode": "MS"
                        },
                        {
                            "name": "Standard",
                            "reference": "STANDARD",
                            "type": "OTHER",
                            "mode": "MS"
                        }
                    ],
                    "manufacturer": "Denon",
                    "modelName": "AVR-3312CI"
                },
                {
                    "name": "Receiver Zone 2",
                    "host": "192.168.1.143",
                    "port": 80,
                    "refreshInterval": 5,
                    "zoneControl": 1,
                    "volumeControl": 1,
                    "switchInfoMenu": false,
                    "inputs": [
                        {
                            "name": "Source",
                            "reference": "SOURCE",
                            "type": "OTHER",
                            "mode": "SI"
                        },
                        {
                            "name": "-21 dB",
                            "reference": "QUICK1",
                            "type": "OTHER",
                            "mode": "SI"
                        },
                        {
                            "name": "-26 dB",
                            "reference": "QUICK2",
                            "type": "OTHER",
                            "mode": "SI"
                        }
                    ]
                }
            ],
            "platform": "DenonTv"
        }
```

**Comment by grzegorz914** [comment]
try 10.31

**Comment by chetstone** [comment]
I tried 3.10.31. Now I'm getting this error:

```
[3/29/2021, 2:46:44 PM] [DenonTv] Device: 192.168.1.143 Receiver Main, parse or write string error: TypeError: Cannot read property 'BrandCode' of undefined
    at denonTvDevice.getDeviceInfo (/opt/homebrew/lib/node_modules/homebridge-denon-tv/index.js:175:42)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
[3/29/2021, 2:46:44 PM] [DenonTv] Device: 192.168.1.143 Receiver Zone 2, parse or write string error: TypeError: Cannot read property 'BrandCode' of undefined
    at denonTvDevice.getDeviceInfo (/opt/homebrew/lib/node_modules/homebridge-denon-tv/index.js:175:42)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

**Comment by grzegorz914** [comment]
try .33
