### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]

### ISSUE THREAD

**Issue by dbsqp** [grzegorz914/homebridge-denon-tv#83]
Hi am getting the following error for my Marantz NR1602 using v3.8.21 under v1.3.3-beta.4.

[homebridge-denon-tv] Device: 10.0.0.43 Mode, Device Info eror: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined, state: Offline, trying to reconnect

**Comment by grzegorz914** [comment]
Still this exist with latest release?

**Comment by lzparkma** [comment]
I still get the following error using v3.10.27 under v1.3.4:

[3/25/2021, 6:23:32 PM] [homebridge-denon-tv] Device: 10.0.0.43 Source, parse string error: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined

**Comment by grzegorz914** [comment]
Please enable debug Mode and get The log.

**Comment by lzparkma** [comment]
Where is the debug log or how do I enable it?

**Comment by grzegorz914** [comment]
Please update to the latest version, i have fixed this error.

**Comment by dbsqp** [comment]
I am still get the error using 3.10.30 under v1.3.4:

[3/28/2021, 9:26:25 PM] [homebridge-denon-tv] Device: 10.0.0.43 Source, parse string error: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined

**Comment by grzegorz914** [comment]
Please enable debug Mode and get The log.

**Comment by dbsqp** [comment]
[3/29/2021, 10:32:36 PM] [DenonTv] Initializing DenonTv platform...
[3/29/2021, 10:32:36 PM] [DenonTv] Initializing child bridge 0E:CE:3B:45:D8:83                       
[3/29/2021, 10:32:39 PM] Registering platform 'homebridge-denon-tv.DenonTv'
[3/29/2021, 10:32:39 PM] [homebridge-denon-tv] Loaded homebridge-denon-tv v3.10.30 child bridge successfully
[3/29/2021, 10:32:39 PM] Loaded 0 cached accessories from cachedAccessories.0ECE3B45D883.
Preparing Advertiser for 'homebridge-denon-tv 52F7' using ciao backend!
[3/29/2021, 10:32:39 PM] [homebridge-denon-tv] didFinishLaunching
[3/29/2021, 10:32:39 PM] [homebridge-denon-tv] prepareAccessory
[3/29/2021, 10:32:39 PM] [homebridge-denon-tv] prepareInformationService
[3/29/2021, 10:32:39 PM] [homebridge-denon-tv] Device: 10.0.0.43 Source, read devInfo: {}
Starting to advertise 'homebridge-denon-tv 52F7' using ciao backend!
[3/29/2021, 10:32:39 PM] Homebridge v1.3.4 (homebridge-denon-tv) is running on port 38800.
(node:23188) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at denonTvDevice.prepareAccessory (/homebridge/node_modules/homebridge-denon-tv/index.js:290:78)
    at new denonTvDevice (/homebridge/node_modules/homebridge-denon-tv/index.js:164:9)
    at HomebridgeAPI.<anonymous> (/homebridge/node_modules/homebridge-denon-tv/index.js:46:6)
    at HomebridgeAPI.emit (events.js:315:20)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/homebridge/src/api.ts:275:10)
    at ChildBridgeFork.startBridge (/usr/local/lib/node_modules/homebridge/src/childBridgeFork.ts:173:14)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:23188) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:23188) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

[3/29/2021, 10:32:59 PM] [homebridge-denon-tv] Device: 10.0.0.43 Source, requesting Device Info.
[3/29/2021, 10:32:59 PM] [homebridge-denon-tv] Device: 10.0.0.43 Source, debug response: <html><head><title>Document Error: Data follows</title></head>
		<body><h2>Access Error: Data follows</h2>
		<p>Form Deviceinfo.xml is not defined</p></body></html>

[3/29/2021, 10:32:59 PM] [homebridge-denon-tv] Device: 10.0.0.43 Source, parse string error: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined

[3/29/2021, 10:32:59 PM] [homebridge-denon-tv] Device: 10.0.0.43 Source, requesting Device state.
[3/29/2021, 10:32:59 PM] [homebridge-denon-tv] Device: 10.0.0.43 Source, debug response: <?xml version="1.0" encoding="utf-8" ?>
<item>
<Power><value>ON</value></Power>
<InputFuncSelect><value>DVD</value></InputFuncSelect>
<MasterVolume><value>-37.0</value></MasterVolume>
<Mute><value>off</value></Mute>
</item>
, result: { item: [Object] }

**Comment by dbsqp** [comment]
`[3/29/2021, 10:32:36 PM] [DenonTv] Initializing DenonTv platform...
[3/29/2021, 10:32:36 PM] [DenonTv] Initializing child bridge 0E:CE:3B:45:D8:83                       
[3/29/2021, 10:32:39 PM] Registering platform 'homebridge-denon-tv.DenonTv'
[3/29/2021, 10:32:39 PM] [homebridge-denon-tv] Loaded homebridge-denon-tv v3.10.30 child bridge successfully
[3/29/2021, 10:32:39 PM] Loaded 0 cached accessories from cachedAccessories.0ECE3B45D883.
Preparing Advertiser for 'homebridge-denon-tv 52F7' using ciao backend!
[3/29/2021, 10:32:39 PM] [homebridge-denon-tv] didFinishLaunching
[3/29/2021, 10:32:39 PM] [homebridge-denon-tv] prepareAccessory
[3/29/2021, 10:32:39 PM] [homebridge-denon-tv] prepareInformationService
[3/29/2021, 10:32:39 PM] [homebridge-denon-tv] Device: 10.0.0.43 Source, read devInfo: {}
Starting to advertise 'homebridge-denon-tv 52F7' using ciao backend!
[3/29/2021, 10:32:39 PM] Homebridge v1.3.4 (homebridge-denon-tv) is running on port 38800.
(node:23188) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at denonTvDevice.prepareAccessory (/homebridge/node_modules/homebridge-denon-tv/index.js:290:78)
    at new denonTvDevice (/homebridge/node_modules/homebridge-denon-tv/index.js:164:9)
    at HomebridgeAPI.<anonymous> (/homebridge/node_modules/homebridge-denon-tv/index.js:46:6)
    at HomebridgeAPI.emit (events.js:315:20)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/homebridge/src/api.ts:275:10)
    at ChildBridgeFork.startBridge (/usr/local/lib/node_modules/homebridge/src/childBridgeFork.ts:173:14)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:23188) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:23188) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

[3/29/2021, 10:32:59 PM] [homebridge-denon-tv] Device: 10.0.0.43 Source, requesting Device Info.
[3/29/2021, 10:32:59 PM] [homebridge-denon-tv] Device: 10.0.0.43 Source, debug response: <html><head><title>Document Error: Data follows</title></head>
		<body><h2>Access Error: Data follows</h2>
		<p>Form Deviceinfo.xml is not defined</p></body></html>

[3/29/2021, 10:32:59 PM] [homebridge-denon-tv] Device: 10.0.0.43 Source, parse string error: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined

[3/29/2021, 10:32:59 PM] [homebridge-denon-tv] Device: 10.0.0.43 Source, requesting Device state.
[3/29/2021, 10:32:59 PM] [homebridge-denon-tv] Device: 10.0.0.43 Source, debug response: <?xml version="1.0" encoding="utf-8" ?>
<item>
<Power><value>ON</value></Power>
<InputFuncSelect><value>DVD</value></InputFuncSelect>
<MasterVolume><value>-37.0</value></MasterVolume>
<Mute><value>off</value></Mute>
</item>
, result: { item: [Object] }`

**Comment by dbsqp** [comment]
> [3/29/2021, 10:32:36 PM] [DenonTv] Initializing DenonTv platform...
[3/29/2021, 10:32:36 PM] [DenonTv] Initializing child bridge 0E:CE:3B:45:D8:83                       
[3/29/2021, 10:32:39 PM] Registering platform 'homebridge-denon-tv.DenonTv'
[3/29/2021, 10:32:39 PM] [homebridge-denon-tv] Loaded homebridge-denon-tv v3.10.30 child bridge successfully
[3/29/2021, 10:32:39 PM] Loaded 0 cached accessories from cachedAccessories.0ECE3B45D883.
Preparing Advertiser for 'homebridge-denon-tv 52F7' using ciao backend!
[3/29/2021, 10:32:39 PM] [homebridge-denon-tv] didFinishLaunching
[3/29/2021, 10:32:39 PM] [homebridge-denon-tv] prepareAccessory
[3/29/2021, 10:32:39 PM] [homebridge-denon-tv] prepareInformationService
[3/29/2021, 10:32:39 PM] [homebridge-denon-tv] Device: 10.0.0.43 Source, read devInfo: {}
Starting to advertise 'homebridge-denon-tv 52F7' using ciao backend!
[3/29/2021, 10:32:39 PM] Homebridge v1.3.4 (homebridge-denon-tv) is running on port 38800.
(node:23188) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at denonTvDevice.prepareAccessory (/homebridge/node_modules/homebridge-denon-tv/index.js:290:78)
    at new denonTvDevice (/homebridge/node_modules/homebridge-denon-tv/index.js:164:9)
    at HomebridgeAPI.<anonymous> (/homebridge/node_modules/homebridge-denon-tv/index.js:46:6)
    at HomebridgeAPI.emit (events.js:315:20)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/homebridge/src/api.ts:275:10)
    at ChildBridgeFork.startBridge (/usr/local/lib/node_modules/homebridge/src/childBridgeFork.ts:173:14)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:23188) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:23188) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

[3/29/2021, 10:32:59 PM] [homebridge-denon-tv] Device: 10.0.0.43 Source, requesting Device Info.
[3/29/2021, 10:32:59 PM] [homebridge-denon-tv] Device: 10.0.0.43 Source, debug response: <html><head><title>Document Error: Data follows</title></head>
		<body><h2>Access Error: Data follows</h2>
		<p>Form Deviceinfo.xml is not defined</p></body></html>

[3/29/2021, 10:32:59 PM] [homebridge-denon-tv] Device: 10.0.0.43 Source, parse string error: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined

[3/29/2021, 10:32:59 PM] [homebridge-denon-tv] Device: 10.0.0.43 Source, requesting Device state.
[3/29/2021, 10:32:59 PM] [homebridge-denon-tv] Device: 10.0.0.43 Source, debug response: <?xml version="1.0" encoding="utf-8" ?>
<item>
<Power><value>ON</value></Power>
<InputFuncSelect><value>DVD</value></InputFuncSelect>
<MasterVolume><value>-37.0</value></MasterVolume>
<Mute><value>off</value></Mute>
</item>
, result: { item: [Object] }

**Comment by dbsqp** [comment]
[homebridge.log.txt](https://github.com/grzegorz914/homebridge-denon-tv/files/6224465/homebridge.log.txt)

**Comment by grzegorz914** [comment]
try latest update
