### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by hotdotdev** [grzegorz914/homebridge-denon-tv#86]
homebridge-denon-tv v3.9.0-beta.17 seems to have problems:
I got this error and the hb does not start:

```
TypeError: Cannot read property 'length' of undefined
    at new denonTvDevice (/usr/local/lib/node_modules/homebridge-denon-tv/index.js:94:65)
    at HomebridgeAPI.<anonymous> (/usr/local/lib/node_modules/homebridge-denon-tv/index.js:45:6)
    at HomebridgeAPI.emit (events.js:327:22)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/homebridge/src/api.ts:275:10)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:173:14)
```

**Comment by Seexelas** [comment]
Hello

Same problem for me since the last update. Homebridge instance won't start.

**Comment by Seexelas** [comment]
Last update corrected the issue, thanks a lot

**Comment by hotdotdev** [comment]
Thanks, it is solved!
