### ISSUE TITLE
404 when trying to communicate with my X3300-W avr

### ISSUE THREAD

**Issue by witchdrash** [grzegorz914/homebridge-denon-tv#98]
`[4/6/2021, 11:52:41 AM] [DenonTv] Device: 192.168.1.74 AV Receiver, requesting Device Info.
[4/6/2021, 11:52:41 AM] [DenonTv] Device: 192.168.1.74 AV Receiver, get device info error: Error: Request failed with status code 404
    at createError (/usr/local/lib/node_modules/homebridge-denon-tv/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/homebridge-denon-tv/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/homebridge-denon-tv/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  config: [Object],
  request: [ClientRequest],
  response: [Object],
  isAxiosError: true,
  toJSON: [Function: toJSON]
}, device offline, trying to reconnect`

**Comment by grzegorz914** [comment]
Check Your network settings, IP, Port, power OFF and ON Receiver, make sure Your AVR is available on the network.
